
const BASEURL = 'https://192.168.1.231:8443/osama/market/';
const LOGIN = 'users/token';
const STORES_LISTING = 'stores?';

const API = {
    BASEURL,
    LOGIN,
    STORES_LISTING
}

const LOGIN_PENDING = 'LOGIN_PENDING';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_ERROR = 'LOGIN_ERROR';
const SAVE_USER_SESSION = 'SAVE_USER_SESSION';
const STORES_PENDING = 'STORES_PENDING';
const STORES_SUCCESS = 'STORES_SUCCESS';
const STORES_ERROR = 'STORES_ERROR';
const ACTION_THINGY = 'ACTION_THINGY';
const ACTIONS = {
    LOGIN_ERROR,
    LOGIN_PENDING,
    LOGIN_SUCCESS,
    SAVE_USER_SESSION,
    STORES_PENDING,
    STORES_SUCCESS,
    STORES_ERROR,
    ACTION_THINGY
}
export {
    API,
    ACTIONS
};